import type { Metadata } from "next";
import { Inter, Roboto_Flex, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { ReactLenis } from 'lenis/react'

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

const robotoFlex = Roboto_Flex({
  variable: "--font-roboto-flex",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${robotoFlex.variable} ${robotoMono.variable} font-sans antialiased`}
        style={{ fontFamily: "var(--font-roboto-flex), system-ui, sans-serif" }}
      >
        <ReactLenis root/>
        {children}
      </body>
    </html>
  );
}
